### ISSUE TITLE
Error when creating accounts and limit to accounts

### ISSUE THREAD

**Issue by baskettcase** [Noctem/MonoGen#6]
`Generic Exception: Traceback (most recent call last):
  File "/path/to/Monocle/venv/lib/python3.6/site-packages/monogen/console.py", line 205, in entry
    elif newline:
UnboundLocalError: local variable 'newline' referenced before assignment`

Only one account was added to the csv file and then I was getting these errors after that. Plus it doesn't look like Monogen keeps in mind the time limit on account creation?

**Comment by mean-jive** [comment]
Getting the same. Using  `monogen -c 5 -e xxx@xxx.xxx.xx -f /Users/xxx/Desktop/accounts2.csv`

Also: `-av True` generates `monogen: error: unrecognized arguments: True`
